<?php

namespace ContainerCwny6Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JTSrz01Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jTSrz01' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jTSrz01'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'id' => ['privates', '.errored..service_locator.jTSrz01.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.jTSrz01": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'id' => 'App\\Entity\\User',
            'doctrine' => '?',
        ]);
    }
}
