<?php

namespace ContainerCwny6Ae;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NilaBYG.App\Entity\Plan' shared service.
     *
     * @return \App\Entity\Plan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NilaBYG": it needs an instance of "App\\Entity\\Plan" but this type has been excluded in "config/services.yaml".');
    }
}
