<?php

namespace ContainerDIR0w5v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BnAcpzAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bnAcpzA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bnAcpzA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'plan' => ['privates', '.errored..service_locator.bnAcpzA.App\\Entity\\Plan', NULL, 'Cannot autowire service ".service_locator.bnAcpzA": it needs an instance of "App\\Entity\\Plan" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'plan' => 'App\\Entity\\Plan',
        ]);
    }
}
