<?php

namespace ContainerNgOhDwd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W43kLzCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W43kLzC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W43kLzC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AdminController::profile' => ['privates', '.service_locator.jTSrz01', 'get_ServiceLocator_JTSrz01Service', true],
            'App\\Controller\\AdminController::withdrawals' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\AdminController::deposits' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\AdminController::investments' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DashboardController::payment' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\DashboardController::transaction' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController::withdrawal' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DashboardController::transfer' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\DashboardController::invest' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DashboardController::plan' => ['privates', '.service_locator.NilaBYG', 'get_ServiceLocator_NilaBYGService', true],
            'App\\Controller\\DashboardController::plans' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController::profile' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController::logout' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\HomeController::regster' => ['privates', '.service_locator.fG4PsCE', 'get_ServiceLocator_FG4PsCEService', true],
            'App\\Controller\\HomeController::login' => ['privates', '.service_locator.Dypathk', 'get_ServiceLocator_DypathkService', true],
            'App\\Controller\\HomeController::email' => ['privates', '.service_locator.Dypathk', 'get_ServiceLocator_DypathkService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AdminController:profile' => ['privates', '.service_locator.jTSrz01', 'get_ServiceLocator_JTSrz01Service', true],
            'App\\Controller\\AdminController:withdrawals' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\AdminController:deposits' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\AdminController:investments' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DashboardController:payment' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\DashboardController:transaction' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController:withdrawal' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DashboardController:transfer' => ['privates', '.service_locator.Jd1QjVv', 'get_ServiceLocator_Jd1QjVvService', true],
            'App\\Controller\\DashboardController:invest' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\DashboardController:plan' => ['privates', '.service_locator.NilaBYG', 'get_ServiceLocator_NilaBYGService', true],
            'App\\Controller\\DashboardController:plans' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController:profile' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\DashboardController:logout' => ['privates', '.service_locator.fIl9B8h', 'get_ServiceLocator_FIl9B8hService', true],
            'App\\Controller\\HomeController:regster' => ['privates', '.service_locator.fG4PsCE', 'get_ServiceLocator_FG4PsCEService', true],
            'App\\Controller\\HomeController:login' => ['privates', '.service_locator.Dypathk', 'get_ServiceLocator_DypathkService', true],
            'App\\Controller\\HomeController:email' => ['privates', '.service_locator.Dypathk', 'get_ServiceLocator_DypathkService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::profile' => '?',
            'App\\Controller\\AdminController::withdrawals' => '?',
            'App\\Controller\\AdminController::deposits' => '?',
            'App\\Controller\\AdminController::investments' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\DashboardController::payment' => '?',
            'App\\Controller\\DashboardController::transaction' => '?',
            'App\\Controller\\DashboardController::withdrawal' => '?',
            'App\\Controller\\DashboardController::transfer' => '?',
            'App\\Controller\\DashboardController::invest' => '?',
            'App\\Controller\\DashboardController::plan' => '?',
            'App\\Controller\\DashboardController::plans' => '?',
            'App\\Controller\\DashboardController::profile' => '?',
            'App\\Controller\\DashboardController::logout' => '?',
            'App\\Controller\\HomeController::regster' => '?',
            'App\\Controller\\HomeController::login' => '?',
            'App\\Controller\\HomeController::email' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:profile' => '?',
            'App\\Controller\\AdminController:withdrawals' => '?',
            'App\\Controller\\AdminController:deposits' => '?',
            'App\\Controller\\AdminController:investments' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\DashboardController:payment' => '?',
            'App\\Controller\\DashboardController:transaction' => '?',
            'App\\Controller\\DashboardController:withdrawal' => '?',
            'App\\Controller\\DashboardController:transfer' => '?',
            'App\\Controller\\DashboardController:invest' => '?',
            'App\\Controller\\DashboardController:plan' => '?',
            'App\\Controller\\DashboardController:plans' => '?',
            'App\\Controller\\DashboardController:profile' => '?',
            'App\\Controller\\DashboardController:logout' => '?',
            'App\\Controller\\HomeController:regster' => '?',
            'App\\Controller\\HomeController:login' => '?',
            'App\\Controller\\HomeController:email' => '?',
        ]);
    }
}
