<?php

namespace ContainerV6cZn6k;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UhSyBWxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uhSyBWx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uhSyBWx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'id' => ['privates', '.errored..service_locator.uhSyBWx.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.uhSyBWx": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'doctrine' => '?',
            'id' => 'App\\Entity\\User',
        ]);
    }
}
