<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOa31Odp\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOa31Odp/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOa31Odp.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOa31Odp\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOa31Odp\App_KernelProdContainer([
    'container.build_hash' => 'Oa31Odp',
    'container.build_id' => '49c55989',
    'container.build_time' => 1722923950,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOa31Odp');
