<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBwgDnSS\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBwgDnSS/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBwgDnSS.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBwgDnSS\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBwgDnSS\App_KernelProdContainer([
    'container.build_hash' => 'BwgDnSS',
    'container.build_id' => 'b4bfede5',
    'container.build_time' => 1722925614,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBwgDnSS');
