<?php

namespace ContainerBwgDnSS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailSenderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\EmailSender' shared autowired service.
     *
     * @return \App\Service\EmailSender
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\Service\\EmailSender'])) {
            return $container->privates['App\\Service\\EmailSender'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\EmailSender'])) {
            return $container->privates['App\\Service\\EmailSender'];
        }

        return $container->privates['App\\Service\\EmailSender'] = new \App\Service\EmailSender(new \Symfony\Component\Mailer\Mailer($a, NULL, $b));
    }
}
