<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgOhDwd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgOhDwd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgOhDwd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgOhDwd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgOhDwd\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgOhDwd',
    'container.build_id' => '8035ec51',
    'container.build_time' => 1722923937,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgOhDwd');
