<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1W9B82\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1W9B82/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB1W9B82.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB1W9B82\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB1W9B82\App_KernelDevDebugContainer([
    'container.build_hash' => 'B1W9B82',
    'container.build_id' => 'e746eb67',
    'container.build_time' => 1722921768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1W9B82');
