<?php

namespace ContainerOa31Odp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_Flasher_InstallCommandService extends App_KernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.flasher.install_command' shared service.
     *
     * @return \Flasher\Symfony\Command\InstallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.flasher.install_command'] = new \Flasher\Symfony\Command\InstallCommand();
    }
}
