<?php

namespace ContainerOa31Odp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\PlanRepository' shared autowired service.
     *
     * @return \App\Repository\PlanRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\PlanRepository'] = new \App\Repository\PlanRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
