<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'balance' => [parent::class, 'balance', null],
        "\0".parent::class."\0".'bonus' => [parent::class, 'bonus', null],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'notifications' => [parent::class, 'notifications', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'plans' => [parent::class, 'plans', null],
        "\0".parent::class."\0".'profit' => [parent::class, 'profit', null],
        "\0".parent::class."\0".'referrals' => [parent::class, 'referrals', null],
        "\0".parent::class."\0".'referred' => [parent::class, 'referred', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'totaldeposit' => [parent::class, 'totaldeposit', null],
        "\0".parent::class."\0".'totalwithdrawal' => [parent::class, 'totalwithdrawal', null],
        "\0".parent::class."\0".'transactions' => [parent::class, 'transactions', null],
        'balance' => [parent::class, 'balance', null],
        'bonus' => [parent::class, 'bonus', null],
        'country' => [parent::class, 'country', null],
        'date' => [parent::class, 'date', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'name' => [parent::class, 'name', null],
        'notifications' => [parent::class, 'notifications', null],
        'password' => [parent::class, 'password', null],
        'phone' => [parent::class, 'phone', null],
        'plans' => [parent::class, 'plans', null],
        'profit' => [parent::class, 'profit', null],
        'referrals' => [parent::class, 'referrals', null],
        'referred' => [parent::class, 'referred', null],
        'roles' => [parent::class, 'roles', null],
        'totaldeposit' => [parent::class, 'totaldeposit', null],
        'totalwithdrawal' => [parent::class, 'totalwithdrawal', null],
        'transactions' => [parent::class, 'transactions', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
